# Generated by Django 3.1.5 on 2021-02-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes_encuestas', '0001_initial'),
        ('preguntas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_respuesta', models.CharField(default='Seleccione tipo de pregunta', max_length=20)),
                ('respuesta', models.TextField(default='Responder')),
            ],
        ),
        migrations.CreateModel(
            name='Vinculacion_respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preguntas.pregunta')),
                ('id_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respuestas.respuesta')),
                ('id_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes_encuestas.solicitud')),
            ],
        ),
    ]
