# Generated by Django 3.1.5 on 2021-02-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correos_wunder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='Ingrese email', max_length=100)),
                ('clave', models.CharField(default='Ingrese clave', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_wunder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='Escribir nombre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso_wunder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_wunder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_wunder.correos_wunder')),
                ('usuario_wunder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_wunder.usuario_wunder')),
            ],
        ),
        migrations.AddField(
            model_name='correos_wunder',
            name='usuario_wunder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_wunder.usuario_wunder'),
        ),
    ]
